apiVersion: v1
kind: Service
metadata:
  name: mygreeterv3-server
  labels:
    app: mygreeterv3-server
  namespace: (V_NAMESPACE)
spec:
  selector:
    app: mygreeterv3-server
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
