apiVersion: v1
kind: Service
metadata:
  name: mygreeterv3-demoserver
  labels:
    app: mygreeterv3-demoserver
  namespace: (V_NAMESPACE)
spec:
  selector:
    app: mygreeterv3-demoserver
  ports:
    - port: 50071
      protocol: TCP
      targetPort: 50071
